require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/forces", type: :request do
  
  # Force. As you add validations to Force, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Force.create! valid_attributes
      get forces_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      force = Force.create! valid_attributes
      get force_url(force)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_force_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      force = Force.create! valid_attributes
      get edit_force_url(force)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Force" do
        expect {
          post forces_url, params: { force: valid_attributes }
        }.to change(Force, :count).by(1)
      end

      it "redirects to the created force" do
        post forces_url, params: { force: valid_attributes }
        expect(response).to redirect_to(force_url(Force.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Force" do
        expect {
          post forces_url, params: { force: invalid_attributes }
        }.to change(Force, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post forces_url, params: { force: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested force" do
        force = Force.create! valid_attributes
        patch force_url(force), params: { force: new_attributes }
        force.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the force" do
        force = Force.create! valid_attributes
        patch force_url(force), params: { force: new_attributes }
        force.reload
        expect(response).to redirect_to(force_url(force))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        force = Force.create! valid_attributes
        patch force_url(force), params: { force: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested force" do
      force = Force.create! valid_attributes
      expect {
        delete force_url(force)
      }.to change(Force, :count).by(-1)
    end

    it "redirects to the forces list" do
      force = Force.create! valid_attributes
      delete force_url(force)
      expect(response).to redirect_to(forces_url)
    end
  end
end
